# Generated by Django 5.2.7 on 2025-10-02 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyagol', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='contact',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='joined_date',
            field=models.DateTimeField(null=True),
        ),
    ]
